defaults:
  - train
  - _self_

n_train: 5_000

mesh:
  _target_: pinnstorch.data.PointCloud
  root_dir: ${paths.data_dir}
  read_data_fn: read_data_fn  # Specify the custom data-reading function

train_datasets:
  - mesh_sampler:
      _target_: pinnstorch.data.MeshSampler
      _partial_: true
      num_sample: ${n_train}
      solution:
        - xx
        - qq
      collection_points:
        - f_xx
        - f_qq

val_dataset:
  - mesh_sampler:
      _target_: pinnstorch.data.MeshSampler
      _partial_: true
      solution:
        - xx
        - qq

pred_dataset:
  - mesh_sampler:
      _target_: pinnstorch.data.MeshSampler
      _partial_: true
      idx_t: 100
      solution:
        - xx
        - qq

net:
  _target_: pinnstorch.models.FCN
  layers: [2, 20, 20, 20, 20, 20, 20, 20, 20, 2]  # Adjust input/output layers for xx and qq
  output_names:
    - xx
    - qq

model:
  extra_variables:
    l1: 0.0
    l2: 0.0

trainer:
  accelerator: gpu
  max_epochs: 250000
  devices: [0]
  deterministic: false
  check_val_every_n_epoch: 250001

train: true
val: true
test: false
optimized_metric:
  error:
    - xx
    - qq
  extra_variables:
    - l1
    - l2

plotting:
  _target_: pinnstorch.utils.plot_navier_stokes  # Adjust this if you have custom plotting functions
  _partial_: true

task_name: loop_solution_pde

hydra:
  searchpath:
    - pkg://pinnstorch/conf